package Models;

public class User {

    private int id;
    private String username;
    private String password;

    public User(int id, String username, String password){
        setId(id);
        setUsername(username);
        setPassword(password);
    }

    // Setters
    public void setId(int id){
        // This should be generated by the database, need to figure out where to do that logic
        this.id = id;
    }

    public void setUsername(String username){
        this.username = username;
    }

    public void setPassword(String password){
        this.password = password;
    }

    // Getters

    public int getId(){
        return id;
    }

    public String getUsername(){
        return username;
    }

    public String getPassword(){
        // This feels wrong
        return password;
    }
}
